
#Dla MainWindow
MAINWINDOW_WIDTH = 800
MAINWINDOW_HEIGHT = 600

MAINWINDOW_TITLE = "WoWTime"

QUIT_BUTTON_LABEL = "Zamknij"
QUIT_BUTTON_X = 100
QUIT_BUTTON_Y = 100
QUIT_BUTTON_WIDTH = 100
QUIT_BUTTON_HEIGHT = 50

STATUSDIALOG_WIDTH = 100
STATUSDIALOG_HEIGHT = 170
STATUSDIALOG_MARGIN_BOTTOM = 0
STATUSDIALOG_MARGIN_LEFT = 40       #dodać automatyczne ustawienia na środku

HIDE_STATUSDIALOG_TIME = 400
SHOW_STATUSDIALOG_TIME = 200

#WoWIcon
WOW_TAKEN_IMAGE = "images/wow.png"

WOWICON_FADE_DURATION = 300