
#Dla MainWindow
MAINWINDOW_WIDTH = 800
MAINWINDOW_HEIGHT = 600

MAINWINDOW_TITLE = "WoWTime"

QUIT_BUTTON_LABEL = "Zamknij"
QUIT_BUTTON_X = 100
QUIT_BUTTON_Y = 100
QUIT_BUTTON_WIDTH = 100
QUIT_BUTTON_HEIGHT = 50



#WoWIcon
WOW_TAKEN_IMAGE = "images/wow.png"

WOWICON_FADE_DURATION = 300